### ISSUE TITLE
Why not enable multithreaded?

### ISSUE THREAD

**Issue by ianfiske** [JuliaOpt/CbcBuilder#1]
Following https://github.com/yingzong/or-tools/commit/25ea3fdd27bd1a8657d32ad068840b1221ef78c7, is there any reason we don't want to build with `--enable-cbc-parallel` option?

Multithreading might be hugely beneficial for MILP solve time.

**Comment by juan-pablo-vielma** [comment]
good catch, thanks! no idea why I was not using it. 
Added the option and it works fine so it made it to today's PR

**Comment by ianfiske** [comment]
@juan-pablo-vielma I noticed that we still don't have `--enable-cbc-parallel` on master.  Is there a reason to delay adding multithreaded?

**Comment by juan-pablo-vielma** [comment]
Strange, I think I did not push the change I used to compile `v2.9.9-1-static-parallel`, but I checked the `CbcBuilder.log` in the tarballs for that release and it is there. Both master and `v0.6.0` point to the appropriate binary release (https://github.com/JuliaOpt/Cbc.jl/blob/eaef881a81d1e5a14dcd8a824c8efad5f6feb546/deps/build.jl#L12) so `Cbc.jl` should have parallel support now. 

Could you please double check if `Cbc.jl` `v0.6.0` seems to have parallel support on your end. In the meantime I will update the builder code in master and figure out how to get the right source in the `v2.9.9-1-static-parallel` release.

**Comment by ianfiske** [comment]
Ah, interesting -- I initially just looked at the build files here and saw it wasn't enabled yet.

I just tried updated Cbc and re-started Julia.  I solved a problem with `threads=8` argument.  Good news:  looks like multi-threads are enabled because I see

```
Cbc0030I Thread 0 used 0 times,  waiting to start 0.3276031, 0 cpu time, 0 locks, 0 locked, 0 waiting for locks
Cbc0030I Thread 1 used 0 times,  waiting to start 0.29243016, 0 cpu time, 0 locks, 0 locked, 0 waiting for locks
Cbc0030I Thread 2 used 0 times,  waiting to start 0.25520301, 0 cpu time, 0 locks, 0 locked, 0 waiting for locks
Cbc0030I Thread 3 used 0 times,  waiting to start 0.21724486, 0 cpu time, 0 locks, 0 locked, 0 waiting for locks
Cbc0030I Thread 4 used 0 times,  waiting to start 0.17711115, 0 cpu time, 0 locks, 0 locked, 0 waiting for locks
Cbc0030I Thread 5 used 0 times,  waiting to start 0.13828516, 0 cpu time, 0 locks, 0 locked, 0 waiting for locks
Cbc0030I Thread 6 used 0 times,  waiting to start 0.09826088, 0 cpu time, 0 locks, 0 locked, 0 waiting for locks
Cbc0030I Thread 7 used 0 times,  waiting to start 0.054888964, 0 cpu time, 0 locks, 0 locked, 0 waiting for locks
Cbc0030I Main thread 0 waiting for threads,  1 locks, 3.0994415e-06 locked, 0 waiting for locks
```
In the Cbc logs.  However, the bad news, is that there is no speed gain over 1 thread.  And you can see the messages that `Thread X used 0 times` for each of the 8 threads.  This may be more of a Cbc question than a Cbc.jl question, but any idea why it may not be using these threads?

**Comment by juan-pablo-vielma** [comment]
Yes, it probably is (partially) a `Cbc` issue. Or it could just be that for the specific problem you tried `Cbc` does not think it is useful to use more than one thread. If you post more details I am happy to help track this down. Maybe we can come up with a test to make sure `Cbc.jl` has parallel working.

**Comment by ianfiske** [comment]
Thank you for the generous offer to help track this down!  Is there any additional detail that I can provide without sharing private data?  I'm looking through the Cbc logs for any suggestion of where it decides that it should use the threads.

I'll give some thought to your suggestion that we can come up with a test for parallel Cbc.  I wonder if there is any known problem that should trigger parallel Cbc.

**Comment by ianfiske** [comment]
Just double checking that things are plumbed to make parallel work:  I looked at the static-parallel tag (https://github.com/JuliaOpt/CbcBuilder/blob/v2.9.9-1-static-parallel/build_tarballs.jl).  There is no `--enable-cbc-parallel` option checked.  Is this the correct script that builds the release referenced by Cbc.jl (https://github.com/JuliaOpt/CbcBuilder/releases/download/v2.9.9-1-static-parallel).  If so, it seems like that binary still does not have parallel support.

**Comment by juan-pablo-vielma** [comment]
No, both https://github.com/JuliaOpt/CbcBuilder/blob/v2.9.9-1-static-parallel/build_tarballs.jl, 
https://github.com/JuliaOpt/CbcBuilder/archive/v2.9.9-1-static-parallel.zip and 
https://github.com/JuliaOpt/CbcBuilder/archive/v2.9.9-1-static-parallel.tar.gz have the wrong script. The `build_tarballs.jl` that was actually run to build the binaries can be found inside each tarball (e.g. 
https://github.com/JuliaOpt/CbcBuilder/releases/download/v2.9.9-1-static-parallel/CbcBuilder.v2.9.9.x86_64-linux-gnu-gcc8.tar.gz) in `logs\CbcBuilder.log`. 
So I need to update the release to reflect this and avoid confusion.

**Comment by juan-pablo-vielma** [comment]
Ok, there is no easy way to update the release so I added a note to the release linking to a "shadow" release https://github.com/JuliaOpt/CbcBuilder/releases/tag/v2.9.9-1-static-parallel-real just in case.

**Comment by ianfiske** [comment]
Ah, thank you for that clarification.

**Comment by ianfiske** [comment]
Just following up on this, I did eventually find a scenario that triggers a multi-threaded Cbc run on my machine, so Cbc.jl seems to be working with parallel support.  Thank you for enabling it.  Not sure if I can build a test case for it right away though.

**Comment by juan-pablo-vielma** [comment]
No problem, let me know if you have any ideas. I added a issue to Cbc for such test: JuliaOpt/Cbc.jl#112
